FROM node:20-alpine as builder

WORKDIR /usr/src/app

COPY package.json package.json
COPY package-lock.json package-lock.json

COPY transmissionEndpoint.js transmissionEndpoint.js

RUN npm ci

FROM node:20-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/package.json package.json
COPY --from=builder /usr/src/app/node_modules/ node_modules/
COPY --from=builder /usr/src/app/transmissionEndpoint.js transmissionEndpoint.js

EXPOSE 3000

CMD ["node", "transmissionEndpoint.js"]
