name: ai-pipeline

services:
  temporal-dev-server:
    extends: 
      file: ../../../temporal-architecture/common.yaml
      service: temporal-dev-server
    ports:
      - 7237:7233
      - 8237:8233

  postgres:
    extends: 
      file: ../../../temporal-architecture/common.yaml
      service: postgres
    restart: always
    environment:
       - POSTGRES_HOST_AUTH_METHOD=trust
       - POSTGRES_PASSWORD=dbpassword
       - POSTGRES_USER=dbuser
       - POSTGRES_DB=vector_db

  localstack:
    image: localstack/localstack:s3-latest
    ports:
      - 4566:4566
    environment:
      - DEBUG=${DEBUG:-0}
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=testUser
      - AWS_SECRET_ACCESS_KEY=testAccessKey
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  process-documents-worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      temporal-dev-server:
        condition: service_healthy
      localstack:
        condition: service_healthy
      postgres:
        condition: service_started
    restart: always
    environment:
      - TEMPORAL_ADDRESS=temporal-dev-server:7233
      - AWS_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=testUser
      - AWS_SECRET_ACCESS_KEY=testAccessKey
      - DATABASE_CONNECTION_STRING=postgres://dbuser:dbpassword@postgres:5432/vector_db
      - DATABASE_TABLE_NAME=vector_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./src:/usr/src/app/src
    command: >
      sh -c '\
        sleep 10 \
        && npx nodemon --watch src --ext ts src/process-documents-worker.ts \
      '

  prompt-worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      temporal-dev-server:
        condition: service_healthy
      localstack:
        condition: service_healthy
      postgres:
        condition: service_started
    restart: always
    environment:
      - TEMPORAL_ADDRESS=temporal-dev-server:7233
      - AWS_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=testUser
      - AWS_SECRET_ACCESS_KEY=testAccessKey
      - DATABASE_CONNECTION_STRING=postgres://dbuser:dbpassword@postgres:5432/vector_db
      - DATABASE_TABLE_NAME=vector_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./src:/usr/src/app/src
    command: >
      sh -c '\
        sleep 10 \
        && npx nodemon --watch src --ext ts src/invoke-prompt-worker.ts \
      '

  test-prompts-worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      temporal-dev-server:
        condition: service_healthy
      localstack:
        condition: service_healthy
      postgres:
        condition: service_started
    restart: always
    environment:
      - TEMPORAL_ADDRESS=temporal-dev-server:7233
      - AWS_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=testUser
      - AWS_SECRET_ACCESS_KEY=testAccessKey
      - DATABASE_CONNECTION_STRING=postgres://dbuser:dbpassword@postgres:5432/vector_db
      - DATABASE_TABLE_NAME=vector_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
    command: >
      sh -c '\
        sleep 10 \
        && npx nodemon --watch src --ext ts src/test-prompts-worker.ts \
      '