name: hello-world

services:
  temporal-dev-server: 
    extends: 
      file: ../../../temporal-architecture/common.yaml
      service: temporal-dev-server
    ports:
      - 7234:7233
      - 8234:8233
  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      temporal-dev-server:
        condition: service_healthy
    restart: always
    environment:
      - TEMPORAL_PORT=temporal-dev-server:7234
      - TEMPORAL_NAMESPACE=default
      - TEMPORAL_QUEUE=hello-world
    volumes:
      - ./:/app