services:
  temporal-dev-server:
    container_name: temporal-dev-server
    image: debian:buster
    command: >
      bash -c '\
        apt update && \
        apt install -y curl && \
        curl -sSf https://temporal.download/cli.sh | sh && \
        PATH="\$PATH:/root/.temporalio/bin" >> ~/.bashrc && \
        source ~/.bashrc && \
        temporal server start-dev --namespace default --ip 0.0.0.0
      '
    ports:
      - 7233:7233
      - 8233:8233
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8233/ || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 3
  worker:
    container_name: temporal-data-fetching-java
    build:
      context: ../../
      dockerfile: kotlin/data-fetching/Dockerfile.dev
    depends_on:
      temporal-dev-server:
        condition: service_healthy
    restart: always
    environment:
      # Enable live reload
      - SPRING_PROFILES_ACTIVE=dev
      - TEMPORAL_ADDRESS=temporal-dev-server:7233
      - TEMPORAL_NAMESPACE=default
      - TEMPORAL_QUEUE=data-fetching-kotlin
      # - TEMPORAL_CERT=/app/certs/client.crt
      # - TEMPORAL_KEY=/app/certs/client.key
    volumes:
      - ../../certs:/app/certs
      - ../../kotlin/data-fetching:/app/kotlin/data-fetching
      - /app/kotlin/data-fetching/build