#!/bin/bash

folders=("golang" "kotlin")
json="{}"

array_to_json_array() {
    local arr=("$@")
    local json_array="["

    for folder in "${arr[@]}"; do
        json_array+="\"$folder\","
    done

    json_array="${json_array%,}]"

    echo "$json_array"
}

for folder in "${folders[@]}"; do
    if [ -d "$folder" ]; then
        subfolders=($(ls -d "$folder"/*/ 2>/dev/null))

        for i in "${!subfolders[@]}"; do
            subfolders[$i]=$(basename "${subfolders[$i]}")
        done

        subfolder_json=$(array_to_json_array "${subfolders[@]}")
        json=$(jq --arg key "$folder" --argjson value "$subfolder_json" '.[$key] = $value' <<<"$json")
    fi
done

echo "$json"
