#!/usr/bin/env node

const fs = require("fs")

const languages = ["golang", "kotlin"]

const results = languages
  .flatMap((language) => fs.readdirSync(language)
  .map((project) => {
    return {
      language,
      project
    }
  }));

console.log(JSON.stringify(results, null, 2))