{
 "title": "Replay Giveaway Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Next Giveaway",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Winners",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wins" }
   ]
  },
  {
   "title": "Giveaway Signups",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "signups" }
   ]
  },
  {
   "title": "Schedule to Start Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(temporal_workflow_task_schedule_to_start_latency_count[5m]) / rate(temporal_workflow_task_schedule_to_start_latency_sum[5m])"
    }
   ]
  },
  {
   "title": "Sync Match Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(temporal_cloud_v0_poll_success_sync_count[5m]) / rate(temporal_cloud_v0_poll_success_count[5m])) * 100"
    }
   ]
  },
  {
   "title": "Total Action Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "temporal_cloud_v0_total_action_count"
    }
   ]
  }
 ]
}