name: CI

on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [published]
    

jobs:
  get-projects:
    runs-on: ubuntu-latest
    outputs:
      projectsMatrix: ${{ steps.list-projects.outputs.projectsMatrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get list of Golang project folders
        id: list-projects
        run: |
          set -eux
          PROJECTS_JSON=$(./scripts/generate-examples-matrix)
          echo "projectsMatrix=$PROJECTS_JSON" >> $GITHUB_OUTPUT

      - name: Display JSON output
        run: 'echo "Projects: ${{ steps.list-projects.outputs.projectsMatrix }}"'

  run-jobs:
    needs:
      - get-projects
    strategy:
      matrix: ${{ fromJson(needs.get-projects.outputs.projectsMatrix) }}
    uses: ./.github/workflows/${{ matrix.language }}.yaml
    with:
      project: ${{ matrix.project }}
    secrets: inherit